config/routes.rb
Rails.application.routes.draw do
	resources :urls
	root to: "urls#new"
	post '/',       :to => 'urls#create',   :as => :urls_create
	get '/:token/info/edit', :to => 'urls#edit',   :as => :urls_edit
	get '/:token', :to => 'urls#tiny_url', :as => :tiny_url
	get '/:token/info', :to => 'urls#url_info', :as => :url_info



	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Url.rb
class Url < ActiveRecord::Base
	validates_presence_of :link
	validates :link, format: URI::regexp(%w[http https])
	validates_length_of :link, within: 3..255, on: :create, message: "too long"      

	has_many :visitors, dependent: :destroy

  
end

app/models/Visitor.rb
class Visitor < ActiveRecord::Base
	belongs_to :url, :foreign_key => :url_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	before_action :set_hostname, only: [:create]
	before_action :set_url_by_token, only: [:edit,:update, :destroy]
	# before_action :set_url, only: [:update, :destroy]


 def new 
	 @url = Url.new
 end

 def set_hostname
	@hostname = request.base_url+"/" || "http://localhost:3000/"
 end

def edit
end
 

def tiny_url(token = "")
	@url = Url.find_by_token(params[:token])   # get token from query parameter 
	if !@url.nil?
		@url.viewCount = @url.viewCount+ 1         # increase view count by one for every new visit
		@url.save
		@visitor = @url.visitors.create(ip: request.remote_ip)  # store the ip address in visitor table
		@visitor.save
		redirect_to @url.link
	else
		redirect_to urls_path, notice: 'There is no matching URL found with that token' 
	end
 end

 def url_info
  @url = Url.find_by_token(params[:token])
  if !@url.nil?
	@url
  else
	redirect_to urls_path, notice: 'There is no matching URL found with that token' 
  end
 end

 def generate_token
	token_range = [*'0'..'9',*'A'..'Z',*'a'..'z'] #setting up this array to generate alphanumeric number
	token = Array.new(7){ token_range.sample }.join  #generates a 7 digit alphanumeric number   
 end

 def index
	redirect_to urls_create_path
 end

 def create
	@url = Url.new(url_params)    # create object from trusted params
	token = generate_token        
	if(Url.find_by_token(token))  # Verify if this token is already present in db. if present, create another
		token = generate_token
	end
	@url.token = token  # saving token in this field
	@url.tiny_url = @hostname + @url.token  # saving complete tiny url in this field
	respond_to do |format|
	  if @url.save
		 format.html { redirect_to url_info_path(:token => @url.token), notice: 'Url was successfully created.' }
	  else
		 format.html { render :new }
	  end
	end
 end

 def update
	respond_to do |format|
	  if @url.update(url_params)

		 format.html { redirect_to url_info_path(:token => @url.token), notice: 'Url was successfully updated.' }
	  else
		 format.html { render :edit }
	  end
	end
 end


 def destroy
	@url.destroy
	respond_to do |format|
	  format.html { redirect_to urls_create_path, notice: 'Url was successfully destroyed.' }
	end
 end


 private

 def set_url_by_token
	@url = Url.find_by_token(params[:token]) 
	@url = Url.find(params[:id])  if @url.nil?
 end

 # Never trust parameters from the scary internet, only allow the white list through.
 def url_params
	params.require(:url).permit(:link,:id)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>TinyURL</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
	<% if  @url.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize( @url.errors.count, "error") %> prohibited this url from being saved:</h2>

			<ul>
			<% @url.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

<%= hidden_field_tag 'token', @url.token %>
	<div class="field">
		<%= f.label :enter_url %>
		<%= f.text_area(:link, rows: 1,cols: 60, data: {provide: "markdown"})%>
	</div>
<br>
<br>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing URL</h1>

<%= form_for(@url) do |f| %>
  <% if  @url.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize( @url.errors.count, "error") %> prohibited this url from being saved:</h2>

	  <ul>
	  <% @url.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	  <% end %>
	  </ul>
	</div>
  <% end %>

  <div class="field">
	<%= f.label :enter_url %>
	<%= f.text_area(:link, rows: 1,cols: 60, data: {provide: "markdown"})%>
  </div>
<br>
<br>

  <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

app/views/urls/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Create a TinyURL</h1>

<%= render 'form', url: @url %>

<br><br><br>

<h1>Recently created 15 URL's</h1>
<% if Url.count > 0 %>
<table class="table">
  <thead>
	<tr>
	  <th>Link</th>
	  <th>Tiny URL</th>
	  <th>Info</th>
	  <th colspan="3"></th>
	</tr>
  </thead>

  <tbody>
	<% Url.order(created_at: :desc).limit(15).each do |url| %>
	  <tr>
		<td><%= url.link %></td>
		<td><%= url.tiny_url %></td>
		<td><%= link_to  url_info_path(:token => url.token), target: :_blank do %> <%=  url_info_path(:token => url.token) %> <% end %></td>
	  </tr>
	<% end %>
  </tbody>
</table>
<% else %>
No URL's created Recently. Try creating Tiny URL's.
<% end %>

app/views/urls/url_info.html.erb
<p id="notice"><%= notice %></p>

<h1>Url</h1>

Try a Different Url :  <%= link_to 'Try a different Url', urls_path, class: "btn btn-primary" %>

<br>
<br>

Edit this Url :<%= link_to 'Edit this Url', urls_edit_path, class: "btn btn-primary" %>
<br>
<br>
Delete this Url :<td><%= link_to 'Destroy', @url, method: :delete, data: { confirm: 'Are you sure?' } %></td>


<br>
<br>
  <table class="table">
  <thead>
	<tr>
		<th>Link</th>       
		<td> <%= @url.link %> </td> 
	</tr>
	<tr>
		<th>Token</th>       
		<td> <%= @url.token %> </td> 
	</tr>
	<tr>
		<th>Tiny Url</th>       
		<td><%= link_to @url.tiny_url, target: :_blank do %> <%= @url.tiny_url %>
		<% end %> </td> 

	</tr>
	<tr>
		<th>Visitors Count</th>       
		<td> <%= @url.viewCount %> </td> 
	</tr>
	</thead>
  </table>
<br><br><br>


  <table class="table border:1px ">
  <thead>
	<tr>
	  <th>Visitor Id</th>
	  <th>Visitor Ip</th>
	</tr>
  </thead>

<% if  @url.viewCount > 0 %>

  <tbody>
  <% @count = 0 %>
	<% @url.visitors.each do |visitor| %>
	  <tr>
		<td> <%= @count += 1 %> </td>
		<td><%= visitor.ip %></td>
	  </tr>
	<% end %>
  </tbody>

  <% else %>
  <tr>
  </tr>
  <tr>
		<td>
   No Visitors, at the moment!!</td>
  <% end %>
</table>
 